---
- name: Remove Apache
  hosts: webservers
  become: yes

  tasks:
  - name: Stop Service
    service:
      name: apache2
      state: stopped
    when:
    - ansible_distribution == "Ubuntu"

  - name: Stop Service
    service:
      name: httpd
      state: stopped
    when:
    - ansible_distribution == "CentOS"

  - name: Delete Web Contents
    file:
      path: /var/www/html
      state: absent

  - name: Stop Service
    service:
      name: apache2
      state: stopped
    when:
    - ansible_distribution == "Ubuntu"
  - name: Remove Apache2 Package
    yum:
      name: httpd
      autoremove: true
      state: absent
    when:
    - ansible_distribution == "CentOS"

