    - name: Create Directory
      file:
        path: "{{ web_document_directory }}"
        state: directory
    - name: Clone git repo 
      git:
        repo: "{{ web_source_url }}"
        dest: "{{ web_document_directory }}" 
        version: "{{ web_source_version }}"
    - name: Install Apache2 Package for Ubuntu
      apt:
        name: apache2
        update_cache: true
        state: present
    - name: Configure Apache2 Service Port for Ubuntu
      template:
        src: ports.conf.j2
        dest: /etc/apache2/ports.conf
        backup: true
      notify:
        - Restart Apache2
    - name: Start/Enable Apache Service for Ubuntu
      service:
        name: apache2
        enabled: true
        state: started
