---
#Play
- name: Install Apache with sb-admin
  hosts: node1
  become: yes
  vars_files:
    - vars/web.yaml

  tasks:
  #Task
  - name: Create Directory
    file:
      #Task Option/Paramater/Argument
      path: "{{ web_document_directory }}"
      state: directory
  - name: Clone git repo 
    git:
      repo: "{{ web_source_url }}"
      dest: "{{ web_document_directory }}" 
      version: "{{ web_source_version }}"
  - name: Install Apache2 Package
    apt:
      name: apache2
      update_cache: true
      state: present
  - name: Configure Apache2 Service Port
    template:
      src: jinja/ports.conf.j2
      dest: /etc/apache2/ports.conf
      backup: true
  ## Important ISSUE!!!!!!!!
  - name: Start/Enable Apache Service
    service:
      name: apache2
      enabled: true
      state: restarted
  ## Important ISSUE!!!!!!!!
  - debug:
      msg: "http://{{ hostvars[inventory_hostname]['ansible_host'] }}:{{ http_port }}"
  - name: Check Local Access
    uri:
      url: "http://{{ hostvars[inventory_hostname]['ansible_host'] }}:{{ http_port }}"
      status_code: 200
      return_content: true
      method: GET

- name: Access Check
  hosts: local
  vars_files:
    - vars/web.yaml

  tasks:
  - name: Check Remote Access
    uri:
      url: "http://{{ hostvars['node1']['ansible_host'] }}:{{ http_port }}"
      status_code: 200
      return_content: true
      method: GET
    register: access_result
  - debug:
      msg: "URL: {{ access_result.url }} / CODE: {{ access_result.status }}"
