---
- name: Remove Apache
  hosts: node1
  become: yes

  tasks:
  - name: Stop Service
    service:
      name: apache2
      state: stopped
  - name: Delete Web Contents
    file:
      path: /var/www/html
      state: absent
  - name: Remove Apache2 Package
    apt:
      name: apache2
      autoremove: true
      state: absent
      purge: true

